services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "80:8000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./app:/usr/src/app
  db:
    build:
      context: .
      dockerfile: db/Dockerfile
    volumes:
      - db_data:/var/lib/postgresql/data
      - init_scripts:/docker-entrypoint-initdb.d
    expose:
      - "5432"
volumes:
  db_data:
  init_scripts: