services:
  app:
    build:
      context: app
      dockerfile: app/Dockerfile
    ports:
      - "80:8000"
    environment:
      - ENV=TEST
    volumes:
      - ./app:/usr/src/app
  db:
    build:
      context: db
      dockerfile: db/Dockerfile
    volumes:
      - init_scripts:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data
    expose:
      - "5432"
volumes:
  db_data:
  init_scripts: