apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: app
          image: entropyscourge/basic-fastapi-app:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: postgres://postgres:password@db:5432/postgres